### ISSUE TITLE
Tensorflow version error

### ISSUE THREAD

**Issue by aniket-9** [ajaytanwani/DIRL#3]
When I run `requirements.py` I am getting the error
`ERROR: Could not find a version that satisfies the requirement tensorflow==1.11.0 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.5.0rc0, 2.5.0rc1)
ERROR: No matching distribution found for tensorflow==1.11.0`

I am using pip 21.0.1, python 3.7.6; do I need to use an older version to get tf 1.11.0? If so, which one?

**Comment by ajaytanwani** [comment]
You would not need to use an older python version. Please just make sure you have the appropriate `cuda` version installed as listed which is compatible with your OS and python version [here](https://www.tensorflow.org/install/source#gpu).
